---
- name: Install VSCode
  tags: VSCODE
  block:
    - homebrew_cask:
        name: visual-studio-code
        state: latest
      when: ansible_distribution == 'MacOSX'
    - yum:
        name: code
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install ansible plugin
  tags: VSCODE
  shell: "/usr/local/bin/code --install-extension {{ item }}"
  loop: "{{ extensions}}"

