---
# tasks file for roles/gpg

- import_tasks: macosx.yml
  when: ansible_facts['distribution'] == "MacOSX"

- import_tasks: rhel.yml
  when: ansible_facts['distribution'] == "Red Hat Enterprise Linux"

- import_tasks: centos.yml
  when: ansible_facts['distribution'] == "CentOS"

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"





