---
- name: Exclude kernel and release from being updated
  lineinfile:
    path: /etc/yum.conf
    regexp: '^exclude='
    line: 'exclude=kernel* redhat-release*'
    owner: root
    group: root
    mode: 0644
  when: ( update_kernal == false and update_release == false )

- name: Clean repos
  command: yum clean all

- name: Install yum updates
  yum:
    name: '*'
    state: latest

- name: Install additional packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - vim
    - unzip
    - wget
    - net-tools
    - smartmontools
    - htop
    - bash-completion
    - bash-completion-extras
    - libguestfs-bash-completion

- name: Update kernel
  command: "yum -y --disableexcludes=main update kernel"
  when: update_kernal == true
  register: kernel_updated

- name: Update release
  command: "yum -y --disableexclude=main update centos-release"
  when: update_relase == true
  register: release_updated

- name: Check if reboot is required
  command: shutdown -r +1  "Update triggered reboot"
  async: 0
  poll: 0
  ignore_errors: yes
  when: kernel_updated|changed or release_updated|changed
  register: rebooting

- name: Waiting for host to reboot
  local_action: wait_for host="{{ inventory_hostname }}" state=started
  become: false
  when: rebooting|changed
