---
- name: Install repos
  yum:
    name: "{{ item }}"
    state:  present
  with_items:
    - epel-release
    - "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm"

- name: Create xrdp.repo
  template:
    src:  xrdp.repo.j2
    dest: /etc/yum.repos.d/xrdp.repo.j2

- name: Install xrdp
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - xrdp
    - tigervnc-server
  notify: restart xrdp

- name: Set xrdp to enabled
  service:
    name: xrdp
    state: started
    enabled: yes

- name: Set iptables
  command: "{{ item }}"
  with_items:
    - "firewall-cmd --permanent --zone=public --add-port=3389/tcp"
    - "firewall-cmd --reload"

- name: Configure SELinux
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    setype: bin_t
  with_items:
    - "/usr/sbin/xrdp"
    - "/usr/sbin/xrdp-sesman"

