---
# - name: Install git
#   homebrew:
#     state: present
#     name: git
#   when: ansible_distribution == "MacOSX"

# - name: Create ~/.gitconfig
#   template:
#       dest: "{{ git_config }}"
#       src: gitconfig.j2
#       owner: "{{ user }}"
#       group: staff
#       mode: 0644

# - name: Create ~/.gitexcludes
#   template:
#       dest: "{{ git_excludes }}"
#       src: gitexcludes.j2
#       owner: "{{ user }}"
#       group: staff
#       mode: 0644


# - name: Check if completion exists
#   stat:
#     path: /usr/local/etc/bash_completion.d/git-completion.bash
#   register: result_completion

# - name: Check if prompt exists
#   stat:
#     path: /usr/local/etc/bash_completion.d/git-prompt.sh
#   register: result_prompt

# - name: Insert GIT_PS1 into bash
#   lineinfile:
#     state: present
#     path: "{{ bash_profile }}"
#     regexp: "{{ item.key }}"
#     line: "{{ item.value }}"
#   loop:
#   - { key: '^GIT_PS1_SHOWDIRTYSTATE', value: 'GIT_PS1_SHOWDIRTYSTATE=true' }
#   - { key: '^export PS1.*.\(__git_ps1\)', value: "export PS1='\\w$(__git_ps1)-$PS1 '" }
